"""Write fix-proposal stubs from probe ERROR findings for human review."""

from __future__ import annotations

from datetime import date
from pathlib import Path
from typing import Iterable

from harness.protocol import Finding, Severity


def _slug(title: str) -> str:
    keep = []
    for ch in title.lower():
        if ch.isalnum():
            keep.append(ch)
        elif keep and keep[-1] != "-":
            keep.append("-")
    return "".join(keep).strip("-")[:60] or "probe-finding"


def proposal_markdown(finding: Finding, *, probe_run_date: str | None = None) -> str:
    """Render a human-review proposal stub from one probe finding."""
    run_date = probe_run_date or date.today().isoformat()
    ev = finding.evidence
    return f"""# Proposal: {finding.title}

Status: **draft — awaiting human review**  
Probe: `{finding.module}`  
Kind: `{finding.kind.value}` / `{finding.severity.value}`  
Generated: {run_date}

## Problem (probe evidence)

{finding.title}

```json
{__import__("json").dumps(ev, indent=2)}
```

## Proposed fix (to be refined)

{ev.get("recommendation", "TBD — assign owner after review.")}

## Scope

- [ ] Architecture / infrastructure
- [ ] Backend API
- [ ] Frontend UI
- [ ] Configuration / deployment (Azure Container Apps)

## Acceptance criteria

- [ ] Probe `{finding.module}` passes against staging
- [ ] Regression test or synthetic journey covers the fixed path
- [ ] Operator doc updated if runbooks change

## Review checklist

- [ ] Root cause confirmed (not just symptom)
- [ ] Fix approach agreed
- [ ] Rollout / rollback plan noted
- [ ] Ready for implementation issue

---
*Auto-generated by OHM triage harness. Edit before approving.*
"""


def write_probe_proposals(
    findings: Iterable[Finding],
    proposals_dir: Path,
    *,
    only_errors: bool = True,
) -> list[Path]:
    """Write proposal markdown files for probe findings. Returns paths written."""
    proposals_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for finding in findings:
        if only_errors and finding.severity != Severity.ERROR:
            continue
        if not finding.module.startswith("probe_"):
            continue
        slug = _slug(finding.title)
        path = proposals_dir / f"{finding.module}-{slug}.md"
        path.write_text(proposal_markdown(finding), encoding="utf-8")
        written.append(path)
    return written
