/**
 * The OHM mark, as data.
 *
 * Two surfaces draw this mark and they must not drift: the inline <Logo>,
 * which reads the live token ramp and re-themes with every world, and the
 * favicon, which is a standalone file that cannot resolve a CSS variable and
 * therefore bakes one world's colours in. Before this module they were two
 * hand-maintained copies of the same path data with a comment asking future
 * editors to remember — which is how the favicon came adrift from the app.
 *
 * So the geometry lives here once, colour arrives as an argument, and
 * `renderMarkSvg` emits the exact bytes of app/icon.svg. src/test/brand.test.ts
 * fails if the checked-in file is not that string, so "remember to update both"
 * is now a test rather than a request. Regenerate with `npm run gen:brand`.
 *
 * No colour literal may appear in this file: it is a component-layer module,
 * and the token layer is the only place a colour is allowed to exist.
 */

export const MARK_VIEWBOX = 32;

/**
 * The mark: a hex nut that is also a network.
 *
 * From across the room it is a hex nut — hardware, unmistakably. Up close its
 * interior is a supply graph: one design resolving into the facilities that
 * can build it, which is the thing the app actually does. The outline breaks
 * at the top, so the hardware is literally open.
 *
 * Not an omega: "OHM" is an acronym for Open Hardware Manager, not the unit of
 * resistance, and a mark punning on that coincidence would advertise something
 * the product is not.
 *
 * Weights are tuned at 16px, not 96px: thinner strokes and smaller nodes turn
 * to mush at favicon scale, where this mark spends most of its life.
 */
export const MARK_STROKE_WIDTH = 2.2;

/** Nut silhouette, opened at the top edge. Two arms from the gap rather than
 *  a closed polygon, so the opening is structural rather than drawn on. */
export const MARK_OUTLINE = "M19.4 3.2 L27.4 8.0 V24.0 L16 29.6 L4.6 24.0 V8.0 L12.6 3.2";

/** Interior edges: the design above, resolving to two makers below. */
export const MARK_EDGES = "M16 12 L10.6 21 M16 12 L21.4 21";

/** Interior nodes, in the same order the edges reach them. */
export const MARK_NODES: ReadonlyArray<{ cx: number; cy: number; r: number }> = [
  { cx: 16, cy: 11.4, r: 3.1 },
  { cx: 10.3, cy: 21.4, r: 2.7 },
  { cx: 21.7, cy: 21.4, r: 2.7 },
];

/** The five iridescent stops, light to dark end, as the ramp is declared. */
export type MarkRamp = readonly [string, string, string, string, string];

/** Gradient stop offsets. Four stops over five ramp tokens — `d` is skipped
 *  because at 16px the c→d step is a hue the eye cannot separate anyway. */
const STOP_OFFSETS = [0, 30, 60, 100] as const;
const RAMP_INDICES = [0, 1, 2, 4] as const;

export interface MarkSvgOptions {
  /** Ramp stops, in --ttm-irid-a..e order. */
  ramp: MarkRamp;
  /** Baked ground behind the mark, so it reads on a dark tab strip. */
  ground: string;
  /** Corner radius of that ground, in viewBox units. */
  groundRadius?: number;
  /** Scale of the mark within the ground, leaving it a little breathing room. */
  inset?: number;
  /** Gradient element id — unique per document when several marks coexist. */
  gradientId?: string;
  /** Accessible name; the mark is the product's name rendered as a shape. */
  label?: string;
}

/**
 * Serialize the mark as a standalone SVG document.
 *
 * Deterministic down to whitespace, because the output is compared byte for
 * byte against the checked-in favicon.
 */
export function renderMarkSvg({
  ramp,
  ground,
  groundRadius = 7,
  inset = 0.86,
  gradientId = "ohm-mark",
  label = "Open Hardware Manager",
}: MarkSvgOptions): string {
  const size = MARK_VIEWBOX;
  const half = size / 2;
  const stops = STOP_OFFSETS.map(
    (offset, i) =>
      `      <stop offset="${offset}%" stop-color="${ramp[RAMP_INDICES[i]]}" />`,
  ).join("\n");
  const nodes = MARK_NODES.map(
    (n) =>
      `    <circle cx="${n.cx}" cy="${n.cy}" r="${n.r}" fill="url(#${gradientId})" />`,
  ).join("\n");

  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${size} ${size}" width="${size}" height="${size}" role="img" aria-label="${label}">
  <!-- GENERATED by npm run gen:brand from src/components/layout/mark.ts.
       Do not hand-edit: src/test/brand.test.ts compares this file byte for
       byte against the generator, so an edit here fails the unit suite.
       The <Logo> component draws the same geometry from the same module but
       reads the live token ramp; a standalone favicon cannot resolve a CSS
       variable, so these stops bake the Warm dark ramp (the default world). -->
  <defs>
    <linearGradient id="${gradientId}" x1="0" y1="0" x2="1" y2="1">
${stops}
    </linearGradient>
  </defs>
  <rect width="${size}" height="${size}" rx="${groundRadius}" fill="${ground}" />
  <g transform="translate(${half} ${half}) scale(${inset}) translate(-${half} -${half})">
    <path
      d="${MARK_OUTLINE}"
      fill="none"
      stroke="url(#${gradientId})"
      stroke-width="${MARK_STROKE_WIDTH}"
      stroke-linecap="round"
      stroke-linejoin="round"
    />
    <path
      d="${MARK_EDGES}"
      fill="none"
      stroke="url(#${gradientId})"
      stroke-width="${MARK_STROKE_WIDTH}"
      stroke-linecap="round"
    />
${nodes}
  </g>
</svg>
`;
}
