"""Canonical suggestion codes for match API responses."""

from typing import Dict

# Stable identifiers intended for API consumers.
SUGGESTION_CODE_NO_FACILITIES_AVAILABLE = "NO_FACILITIES_AVAILABLE"
SUGGESTION_CODE_NO_MATCHING_SOLUTIONS = "NO_MATCHING_SOLUTIONS"
SUGGESTION_CODE_COVERAGE_GAPS_DETECTED = "COVERAGE_GAPS_DETECTED"
SUGGESTION_CODE_COMBINATION_NOT_APPLIED = "COMBINATION_NOT_APPLIED"
SUGGESTION_CODE_ENABLE_FACILITY_COMBINATIONS = "ENABLE_FACILITY_COMBINATIONS"


MATCH_SUGGESTION_CODES: Dict[str, str] = {
    "no_facilities_available": SUGGESTION_CODE_NO_FACILITIES_AVAILABLE,
    "no_matching_solutions": SUGGESTION_CODE_NO_MATCHING_SOLUTIONS,
    "coverage_gaps_detected": SUGGESTION_CODE_COVERAGE_GAPS_DETECTED,
    "combination_not_applied": SUGGESTION_CODE_COMBINATION_NOT_APPLIED,
    "enable_facility_combinations": SUGGESTION_CODE_ENABLE_FACILITY_COMBINATIONS,
}
