import type { JSX } from "react";
import type { IconProps } from "./index";
import {
  ThreeDMaterialPrintingIcon,
  ThreeDObjectIcon,
  ThreeDPrinterIcon,
  AccuracyIcon,
  AiIcon,
  AlgorithmIcon,
  AutomationIcon,
  BenchGrindersIcon,
  BlowerIcon,
  BobbinIcon,
  BrainCommunicationIcon,
  CaliperIcon,
  CementSlinceIcon,
  ChatbotIcon,
  CloudComputingIcon,
  CncIcon,
  CncMachineIcon,
  CognitiveIcon,
  CognitiveComputingIcon,
  ConsistencyIcon,
  ControlIcon,
  CubeIcon,
  CutterIcon,
  DataEntryIcon,
  DataProcessingIcon,
  DataProtectionIcon,
  DecisionMakingIcon,
  DigitalTransformationIcon,
  DrillingMachineIcon,
  EfficiencyIcon,
  ElectricMotorIcon,
  ElectricalPanelIcon,
  ExecutionIcon,
  ExhaustFanIcon,
  FilamentIcon,
  FirstAidBoxIcon,
  FolderIcon,
  GearsIcon,
  GlueGunIcon,
  GrindingMachineIcon,
  HacksawIcon,
  HammerIcon,
  IndustrialIcon,
  IndustrialProductionIcon,
  InnovationIcon,
  IntegrationIcon,
  InternetIcon,
  LaserCutterIcon,
  LatheIcon,
  LayerThicknessIcon,
  LiquidIcon,
  MachineIcon,
  MachineLearningIcon,
  MetalCuttingMachineIcon,
  NotebookIcon,
  OpenAndWrenchIcon,
  OpportunityIcon,
  OptimizationIcon,
  PackingIcon,
  ProcessIcon,
  ProcessImprovementIcon,
  ProductionIcon,
  ProductivityIcon,
  ProgrammingIcon,
  ReduceCostIcon,
  ReliabilityIcon,
  RepetitiveTaskIcon,
  RobotIcon,
  RoboticArmIcon,
  RoboticProcessAutomationIcon,
  SawIcon,
  ScalabilityIcon,
  ScheduleIcon,
  ScissorsIcon,
  ScriptingIcon,
  SelectiveLaserMeltingIcon,
  SetSquareIcon,
  SettingsIcon,
  SmartFactoryIcon,
  SoftwareIcon,
  SolderIcon,
  SolderingStationIcon,
  SprayPaintIcon,
  TaskManagementIcon,
  TeamManagementIcon,
  TestLabIcon,
  ToolBoxIcon,
  UserInterfaceIcon,
  VacuumCleanerIcon,
  VirtualWorkforceIcon,
  ViseIcon,
  VisionIcon,
  WebHostingIcon,
  WeldingIcon,
  WorkflowIcon,
} from "./index";

/**
 * Every glyph, by its source name.
 *
 * Imported only by the `/icons` gallery. Naming all of them in one array
 * defeats tree-shaking for whoever imports it, which is exactly why it is not
 * in `index.tsx` — the gallery is the one page that genuinely wants all of
 * them, and it can pay for them.
 */
export const ALL_ICONS: { name: string; Icon: (props: IconProps) => JSX.Element }[] = [
  { name: "3d-material-printing", Icon: ThreeDMaterialPrintingIcon },
  { name: "3d-object", Icon: ThreeDObjectIcon },
  { name: "3d-printer", Icon: ThreeDPrinterIcon },
  { name: "accuracy", Icon: AccuracyIcon },
  { name: "ai", Icon: AiIcon },
  { name: "algorithm", Icon: AlgorithmIcon },
  { name: "automation", Icon: AutomationIcon },
  { name: "bench-grinders", Icon: BenchGrindersIcon },
  { name: "blower", Icon: BlowerIcon },
  { name: "bobbin", Icon: BobbinIcon },
  { name: "brain-communication", Icon: BrainCommunicationIcon },
  { name: "caliper", Icon: CaliperIcon },
  { name: "cement-slince", Icon: CementSlinceIcon },
  { name: "chatbot", Icon: ChatbotIcon },
  { name: "cloud-computing", Icon: CloudComputingIcon },
  { name: "cnc", Icon: CncIcon },
  { name: "cnc-machine", Icon: CncMachineIcon },
  { name: "cognitive", Icon: CognitiveIcon },
  { name: "cognitive-computing", Icon: CognitiveComputingIcon },
  { name: "consistency", Icon: ConsistencyIcon },
  { name: "control", Icon: ControlIcon },
  { name: "cube", Icon: CubeIcon },
  { name: "cutter", Icon: CutterIcon },
  { name: "data-entry", Icon: DataEntryIcon },
  { name: "data-processing", Icon: DataProcessingIcon },
  { name: "data-protection", Icon: DataProtectionIcon },
  { name: "decision-making", Icon: DecisionMakingIcon },
  { name: "digital-transformation", Icon: DigitalTransformationIcon },
  { name: "drilling-machine", Icon: DrillingMachineIcon },
  { name: "efficiency", Icon: EfficiencyIcon },
  { name: "electric-motor", Icon: ElectricMotorIcon },
  { name: "electrical-panel", Icon: ElectricalPanelIcon },
  { name: "execution", Icon: ExecutionIcon },
  { name: "exhaust-fan", Icon: ExhaustFanIcon },
  { name: "filament", Icon: FilamentIcon },
  { name: "first-aid-box", Icon: FirstAidBoxIcon },
  { name: "folder", Icon: FolderIcon },
  { name: "gears", Icon: GearsIcon },
  { name: "glue-gun", Icon: GlueGunIcon },
  { name: "grinding-machine", Icon: GrindingMachineIcon },
  { name: "hacksaw", Icon: HacksawIcon },
  { name: "hammer", Icon: HammerIcon },
  { name: "industrial", Icon: IndustrialIcon },
  { name: "industrial-production", Icon: IndustrialProductionIcon },
  { name: "innovation", Icon: InnovationIcon },
  { name: "integration", Icon: IntegrationIcon },
  { name: "internet", Icon: InternetIcon },
  { name: "laser-cutter", Icon: LaserCutterIcon },
  { name: "lathe", Icon: LatheIcon },
  { name: "layer-thickness", Icon: LayerThicknessIcon },
  { name: "liquid", Icon: LiquidIcon },
  { name: "machine", Icon: MachineIcon },
  { name: "machine-learning", Icon: MachineLearningIcon },
  { name: "metal-cutting-machine", Icon: MetalCuttingMachineIcon },
  { name: "notebook", Icon: NotebookIcon },
  { name: "open-and-wrench", Icon: OpenAndWrenchIcon },
  { name: "opportunity", Icon: OpportunityIcon },
  { name: "optimization", Icon: OptimizationIcon },
  { name: "packing", Icon: PackingIcon },
  { name: "process", Icon: ProcessIcon },
  { name: "process-improvement", Icon: ProcessImprovementIcon },
  { name: "production", Icon: ProductionIcon },
  { name: "productivity", Icon: ProductivityIcon },
  { name: "programming", Icon: ProgrammingIcon },
  { name: "reduce-cost", Icon: ReduceCostIcon },
  { name: "reliability", Icon: ReliabilityIcon },
  { name: "repetitive-task", Icon: RepetitiveTaskIcon },
  { name: "robot", Icon: RobotIcon },
  { name: "robotic-arm", Icon: RoboticArmIcon },
  { name: "robotic-process-automation", Icon: RoboticProcessAutomationIcon },
  { name: "saw", Icon: SawIcon },
  { name: "scalability", Icon: ScalabilityIcon },
  { name: "schedule", Icon: ScheduleIcon },
  { name: "scissors", Icon: ScissorsIcon },
  { name: "scripting", Icon: ScriptingIcon },
  { name: "selective-laser-melting", Icon: SelectiveLaserMeltingIcon },
  { name: "set-square", Icon: SetSquareIcon },
  { name: "settings", Icon: SettingsIcon },
  { name: "smart-factory", Icon: SmartFactoryIcon },
  { name: "software", Icon: SoftwareIcon },
  { name: "solder", Icon: SolderIcon },
  { name: "soldering-station", Icon: SolderingStationIcon },
  { name: "spray-paint", Icon: SprayPaintIcon },
  { name: "task-management", Icon: TaskManagementIcon },
  { name: "team-management", Icon: TeamManagementIcon },
  { name: "test-lab", Icon: TestLabIcon },
  { name: "tool-box", Icon: ToolBoxIcon },
  { name: "user-interface", Icon: UserInterfaceIcon },
  { name: "vacuum-cleaner", Icon: VacuumCleanerIcon },
  { name: "virtual-workforce", Icon: VirtualWorkforceIcon },
  { name: "vise", Icon: ViseIcon },
  { name: "vision", Icon: VisionIcon },
  { name: "web-hosting", Icon: WebHostingIcon },
  { name: "welding", Icon: WeldingIcon },
  { name: "workflow", Icon: WorkflowIcon },
];
