import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

/**
 * Uniformity guards.
 *
 * A design system decays into suggestions the moment it is only a convention,
 * so the two rules the overhaul actually depends on are asserted here rather
 * than trusted: colour lives in one file, and page chrome is one component.
 *
 * These read source text, which is unusual for a unit test — but the property
 * is about the source, not about rendered output, and rendering every
 * component to discover a stray hex would be slower and less complete.
 */

const SRC = join(import.meta.dirname, "..");

function sourceFiles(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (entry === "generated") continue;
      sourceFiles(full, acc);
    } else if (/\.tsx?$/.test(entry) && !entry.includes(".test.")) {
      acc.push(full);
    }
  }
  return acc;
}

const FILES = sourceFiles(SRC);
const rel = (f: string) => f.slice(SRC.length + 1);

/**
 * Source with comments blanked out, which is what every guard below should be
 * reading.
 *
 * These guards match raw text, so a comment EXPLAINING a rule reads to them
 * exactly like a violation of it. Both new guards tripped on their own
 * documentation the first time they ran — the note recording which hardcoded
 * shade used to live on a checkbox, and the note recording that a component
 * replaced three hand-rolled radio groups. Rewording the prose "fixes" it
 * until the next person writes the next comment, and it quietly pressures
 * people to not write down why a rule exists, which is the opposite of what
 * these files are for.
 *
 * String and template literals are preserved, so a URL's `//` and a class name
 * inside a string are never mistaken for a comment.
 */
function stripComments(src: string): string {
  let out = "";
  let i = 0;
  type Mode = "code" | "line" | "block" | "'" | '"' | "`";
  let mode: Mode = "code";
  while (i < src.length) {
    const two = src.slice(i, i + 2);
    if (mode === "code") {
      if (two === "//") {
        mode = "line";
        i += 2;
        continue;
      }
      if (two === "/*") {
        mode = "block";
        i += 2;
        continue;
      }
      if (src[i] === "'" || src[i] === '"' || src[i] === "`")
        mode = src[i] as Mode;
      out += src[i++];
      continue;
    }
    if (mode === "line") {
      if (src[i] === "\n") {
        mode = "code";
        out += "\n";
      }
      i++;
      continue;
    }
    if (mode === "block") {
      if (two === "*/") {
        mode = "code";
        i += 2;
        continue;
      }
      // Keep newlines so reported line numbers stay meaningful.
      if (src[i] === "\n") out += "\n";
      i++;
      continue;
    }
    // Inside a string or template literal.
    if (src[i] === "\\") {
      out += src.slice(i, i + 2);
      i += 2;
      continue;
    }
    if (src[i] === mode) mode = "code";
    out += src[i++];
  }
  return out;
}

/** Read a source file with its comments removed. */
const code = (f: string) => stripComments(readFileSync(f, "utf8"));

describe("colour lives only in the token layer", () => {
  it("no raw hex colours in components", () => {
    // styles/tokens.css is the token layer itself; button.tsx is regenerated by
    // the shadcn CLI and already reads tokens.
    const offenders = FILES.filter(
      (f) => !rel(f).startsWith("components/ui/button"),
    )
      .map((f) => ({ file: rel(f), hits: code(f).match(/#[0-9a-fA-F]{6}\b/g) }))
      .filter((x) => x.hits)
      .map((x) => `${x.file}: ${x.hits!.join(", ")}`);

    expect(
      offenders,
      `raw hex outside the token layer:\n${offenders.join("\n")}`,
    ).toEqual([]);
  });

  it("no hardcoded Tailwind palette utilities", () => {
    // The palette shades carry no theme; the token utilities do.
    //
    // The prefix list used to be spelled out — bg|text|border|ring|divide|
    // placeholder — and that is exactly how `accent-indigo-600` survived the
    // Phase 7 sweep on a checkbox for a year: the guard was not wrong about
    // any file it looked at, it simply never looked at `accent-`. A guard that
    // enumerates the properties it knows about will always be one property
    // behind the stylesheet, so this matches the SHADE, wherever it appears.
    // Any utility ending in a palette hue plus a numeric step is a colour that
    // no theme can reach, which is the property actually being asserted.
    const palette =
      /\b[a-z-]*(?:slate|gray|zinc|neutral|stone|indigo|blue|red|green|amber|emerald|violet|purple|pink|rose|orange|yellow|teal|cyan|sky|lime)-\d{2,3}\b/g;
    const offenders = FILES.filter(
      (f) => !rel(f).startsWith("components/ui/button"),
    )
      .map((f) => ({ file: rel(f), hits: code(f).match(palette) }))
      .filter((x) => x.hits)
      .map((x) => `${x.file}: ${[...new Set(x.hits!)].join(", ")}`);

    expect(
      offenders,
      `hardcoded palette utilities (use tokens):\n${offenders.join("\n")}`,
    ).toEqual([]);
  });
});

describe("chrome is universal", () => {
  it("only Layout mounts the site chrome", () => {
    // The rule is about SITE chrome, not semantic landmarks: a facet panel or
    // an in-page tab strip should absolutely be a <nav>, and a settings page
    // may have its own <footer>. What must not happen is a second site header
    // or footer, so this asserts on the components rather than the tags.
    const offenders = FILES.filter(
      (f) => rel(f).startsWith("views/") || rel(f).startsWith("features/"),
    )
      .map((f) => ({
        file: rel(f),
        hits: code(f).match(/\b(?:SiteHeader|SiteFooter|NavDrawer)\b/g),
      }))
      .filter((x) => x.hits)
      .map((x) => `${x.file}: ${[...new Set(x.hits!)].join(", ")}`);

    expect(
      offenders,
      `site chrome mounted outside Layout:\n${offenders.join("\n")}`,
    ).toEqual([]);
  });

  it("panels are drawn from the surface constants", () => {
    // The panel is the most-repeated box in the app and had no name, so it
    // drifted into two dozen near-identical spellings: rounded-lg beside
    // rounded-xl, border-input beside border-border, five opacities of one
    // accent wash. `components/ui/surface.ts` names the majority spelling;
    // this keeps the next one from being invented inline.
    //
    // Matched narrowly on purpose — a bordered box WITH a background and
    // padding is a panel. A bare `rounded-md border` on an input group is not,
    // and a guard that fails on correct code trains people to disable guards.
    const adHocPanel =
      /\brounded-(?:lg|xl|2xl)\s+border\s+border-[a-z-]+(?:\/\d+)?\s+bg-[a-z-]+(?:\/\d+)?\s+p-\d/g;
    const offenders = FILES.filter(
      (f) => !rel(f).startsWith("components/ui/surface"),
    )
      .map((f) => ({ file: rel(f), hits: code(f).match(adHocPanel) }))
      .filter((x) => x.hits)
      .map((x) => `${x.file}: ${[...new Set(x.hits!)].join(", ")}`);

    expect(
      offenders,
      `ad-hoc panel classes (use PANEL / PANEL_* from components/ui/surface):\n${offenders.join("\n")}`,
    ).toEqual([]);
  });

  it("one-of-N choices go through SegmentedControl", () => {
    // role="radiogroup" is a promise: it tells a screen reader to announce
    // "1 of 3" and to expect arrow keys to move the selection. All three
    // hand-rolled groups in this app made that promise and implemented no key
    // handling at all, which is worse than plain buttons — the user is told a
    // behaviour exists and then finds it does not.
    //
    // SegmentedControl implements the WAI-ARIA pattern once (roving tabindex,
    // arrows, Home/End). Anything else declaring the role has to implement it
    // again, and the next one will forget again.
    const offenders = FILES.filter(
      (f) => !rel(f).startsWith("components/ui/SegmentedControl"),
    )
      .map((f) => ({
        file: rel(f),
        hits: code(f).match(/role="radiogroup"/g),
      }))
      .filter((x) => x.hits)
      .map((x) => x.file);

    expect(
      offenders,
      `hand-rolled radio groups (use components/ui/SegmentedControl):\n${offenders.join("\n")}`,
    ).toEqual([]);
  });

  it("every fieldset overrides the UA min-content width", () => {
    // <fieldset> is the one element the UA stylesheet gives
    // `min-inline-size: min-content`. It therefore refuses to shrink below its
    // widest descendant no matter what its parent is doing, and takes the
    // page's horizontal scroll with it — that was the /match mobile bug, a
    // 920px facilities panel in a 360px window.
    //
    // Asserted as the PROPERTY, not as "use the Fieldset component". A
    // fieldset is also the right element for a drawer section or a bare group
    // of permission checkboxes, where the component's card styling would be
    // wrong; banning the tag would have pushed those toward <div role="group">
    // and lost real semantics to satisfy a guard. What must never be missing
    // is min-w-0.
    const offenders: string[] = [];
    for (const f of FILES) {
      if (rel(f).startsWith("components/ui/Fieldset")) continue;
      const src = code(f);
      for (const m of src.matchAll(/<fieldset\b([^>]*)>/g)) {
        if (!/\bmin-w-0\b/.test(m[1])) {
          offenders.push(`${rel(f)}: <fieldset${m[1].slice(0, 60)}>`);
        }
      }
    }

    expect(
      offenders,
      `fieldset without min-w-0 — it will not shrink below its widest child.\nUse components/ui/Fieldset, or add min-w-0:\n${offenders.join("\n")}`,
    ).toEqual([]);
  });

  it("headings take their size from the type scale", () => {
    // tokens.css has carried --ttm-fs-* since Phase 2 and nothing read it, so
    // every heading picked a Tailwind step by hand — two sizes for a page
    // title, and one "section label" role spelled text-sm on twenty-two
    // content pages and text-xs in the drawer. Size is a design decision like
    // colour and belongs in the same one place.
    //
    // Scoped to heading TAGS, which is the honest boundary. A `text-sm` on a
    // paragraph or a badge is body copy making a local choice; a heading is a
    // rung on a scale, and picking its size inline is how the scale stopped
    // being one. Roles live in components/ui/typography.ts.
    const hardcoded =
      /<h[1-6]\b[^>]*className="[^"]*\btext-(?:xs|sm|base|lg|xl|[2-9]xl)\b/g;
    const offenders = FILES.map((f) => ({
      file: rel(f),
      hits: code(f).match(hardcoded),
    }))
      .filter((x) => x.hits)
      .map((x) => `${x.file}: ${x.hits!.length}`);

    expect(
      offenders,
      `headings with a hand-picked text size (use components/ui/typography):\n${offenders.join("\n")}`,
    ).toEqual([]);
  });

  it("headings take their weight and colour from the type scale too", () => {
    // The size guard above closed one half of the hole and the other half kept
    // drifting through it: seven card titles spelled `font-semibold
    // text-foreground` inline, which is CARD_TITLE with the rung left off, so
    // they inherited whatever the surrounding text happened to be. A heading
    // that names no role is still a heading picking its own styling.
    const inlineWeight =
      /<h[1-6]\b[^>]*className="[^"]*\bfont-(?:medium|semibold|bold)\b/g;
    const offenders = FILES.map((f) => ({
      file: rel(f),
      hits: code(f).match(inlineWeight),
    }))
      .filter((x) => x.hits)
      .map((x) => `${x.file}: ${x.hits!.length}`);

    expect(
      offenders,
      `headings styled inline (use a role from components/ui/typography):\n${offenders.join("\n")}`,
    ).toEqual([]);
  });

  it("no emoji in rendered UI", () => {
    const emoji = /[\u{1F300}-\u{1FAFF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu;
    const offenders = FILES.filter((f) => !rel(f).startsWith("test/"))
      .map((f) => ({ file: rel(f), hits: code(f).match(emoji) }))
      .filter((x) => x.hits)
      .map((x) => `${x.file}: ${x.hits!.join(" ")}`);

    expect(offenders, `emoji in UI source:\n${offenders.join("\n")}`).toEqual(
      [],
    );
  });
});
