import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

/**
 * Uniformity guards.
 *
 * A design system decays into suggestions the moment it is only a convention,
 * so the two rules the overhaul actually depends on are asserted here rather
 * than trusted: colour lives in one file, and page chrome is one component.
 *
 * These read source text, which is unusual for a unit test — but the property
 * is about the source, not about rendered output, and rendering every
 * component to discover a stray hex would be slower and less complete.
 */

const SRC = join(import.meta.dirname, "..");

function sourceFiles(dir: string, acc: string[] = []): string[] {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) {
      if (entry === "generated") continue;
      sourceFiles(full, acc);
    } else if (/\.tsx?$/.test(entry) && !entry.includes(".test.")) {
      acc.push(full);
    }
  }
  return acc;
}

const FILES = sourceFiles(SRC);
const rel = (f: string) => f.slice(SRC.length + 1);

describe("colour lives only in the token layer", () => {
  it("no raw hex colours in components", () => {
    // styles/tokens.css is the token layer itself; button.tsx is regenerated by
    // the shadcn CLI and already reads tokens.
    const offenders = FILES.filter((f) => !rel(f).startsWith("components/ui/button"))
      .map((f) => ({ file: rel(f), hits: readFileSync(f, "utf8").match(/#[0-9a-fA-F]{6}\b/g) }))
      .filter((x) => x.hits)
      .map((x) => `${x.file}: ${x.hits!.join(", ")}`);

    expect(offenders, `raw hex outside the token layer:\n${offenders.join("\n")}`).toEqual(
      [],
    );
  });

  it("no hardcoded Tailwind palette utilities", () => {
    // The palette shades carry no theme; the token utilities do.
    const palette =
      /\b(?:bg|text|border|ring|divide|placeholder)-(?:slate|gray|zinc|neutral|stone|indigo|blue|red|green|amber|emerald|violet|purple|pink|rose|orange|yellow|teal|cyan|sky|lime)-\d{2,3}\b/g;
    const offenders = FILES.filter((f) => !rel(f).startsWith("components/ui/button"))
      .map((f) => ({ file: rel(f), hits: readFileSync(f, "utf8").match(palette) }))
      .filter((x) => x.hits)
      .map((x) => `${x.file}: ${[...new Set(x.hits!)].join(", ")}`);

    expect(
      offenders,
      `hardcoded palette utilities (use tokens):\n${offenders.join("\n")}`,
    ).toEqual([]);
  });
});

describe("chrome is universal", () => {
  it("only Layout mounts the site chrome", () => {
    // The rule is about SITE chrome, not semantic landmarks: a facet panel or
    // an in-page tab strip should absolutely be a <nav>, and a settings page
    // may have its own <footer>. What must not happen is a second site header
    // or footer, so this asserts on the components rather than the tags.
    const offenders = FILES.filter(
      (f) => rel(f).startsWith("views/") || rel(f).startsWith("features/"),
    )
      .map((f) => ({
        file: rel(f),
        hits: readFileSync(f, "utf8").match(/\b(?:SiteHeader|SiteFooter|NavDrawer)\b/g),
      }))
      .filter((x) => x.hits)
      .map((x) => `${x.file}: ${[...new Set(x.hits!)].join(", ")}`);

    expect(
      offenders,
      `site chrome mounted outside Layout:\n${offenders.join("\n")}`,
    ).toEqual([]);
  });

  it("no emoji in rendered UI", () => {
    const emoji = /[\u{1F300}-\u{1FAFF}\u{2600}-\u{26FF}\u{2700}-\u{27BF}]/gu;
    const offenders = FILES.filter((f) => !rel(f).startsWith("test/"))
      .map((f) => ({ file: rel(f), hits: readFileSync(f, "utf8").match(emoji) }))
      .filter((x) => x.hits)
      .map((x) => `${x.file}: ${x.hits!.join(" ")}`);

    expect(offenders, `emoji in UI source:\n${offenders.join("\n")}`).toEqual([]);
  });
});
