#!/usr/bin/env python3
"""Write a Markdown route table for MkDocs from the versioned FastAPI app OpenAPI schema.

Output is included from docs/api/routes.md via pymdownx.snippets. Regenerate after
route changes:

    uv run python scripts/generate_openapi_routes_md.py

Default output: docs/api/_generated/openapi-route-table.md
"""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path


def _escape_cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def build_markdown(api_v1) -> str:
    schema = api_v1.openapi()
    info = schema.get("info", {})
    version = info.get("version", "")
    title = info.get("title", "API")

    rows: list[tuple[str, str, str, str]] = []
    paths = schema.get("paths") or {}
    method_order = ("get", "post", "put", "patch", "delete")
    for path in sorted(paths.keys()):
        path_item = paths[path] or {}
        for method in method_order:
            if method not in path_item:
                continue
            op = path_item[method] or {}
            summary = op.get("summary") or op.get("operationId") or ""
            tags = op.get("tags") or []
            tag_str = ", ".join(dict.fromkeys(str(t) for t in tags))
            full_path = f"/v1{path}" if path.startswith("/") else f"/v1/{path}"
            rows.append((method.upper(), full_path, str(summary), tag_str))

    lines: list[str] = [
        "<!-- AUTO-GENERATED by scripts/generate_openapi_routes_md.py — do not edit by hand -->",
        "",
        f"_Generated at {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} from **{title}**"
        + (f" v{version}." if version else "."),
        "",
        "| Method | Path | Summary | Tags |",
        "|--------|------|---------|------|",
    ]
    for method, path, summary, tags in rows:
        lines.append(
            f"| `{method}` | `{_escape_cell(path)}` | {_escape_cell(summary)} | {_escape_cell(tags)} |"
        )
    lines.append("")
    lines.append(f"_Total operations: **{len(rows)}**._")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path(__file__).resolve().parent.parent
        / "docs"
        / "api"
        / "_generated"
        / "openapi-route-table.md",
        help="Output Markdown file path",
    )
    args = parser.parse_args()

    from src.core.main import api_v1

    body = build_markdown(api_v1)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(body, encoding="utf-8")
    print(f"Wrote {args.output} ({len(body.splitlines())} lines)")


if __name__ == "__main__":
    main()
